### PR TITLE
Implement all functionalities

### PR DESCRIPTION
**Pull request by lithomas1**
Goals
1. Integrate gui with auto class
2. Make it be able to execute routines
3. Cleanup and refactor(add try catch)

### CODE REVIEW

**Review by KentoNishi — APPROVED** [review]
Looks good!

**Comment by Rahul-Kaura** [comment]
don't merge

**Comment by Rahul-Kaura** [comment]
objectives not accomplished yet

**Comment by KentoNishi** [comment]
- [ ] Integrate gui with auto class
- [ ] Make it be able to execute routines
- [ ] Cleanup and refactor 
    * Add try catch
- [X] Fix login

**Review by KentoNishi — COMMENTED** [review]
Did you sign up on harkerhacks with the link I sent you on hangouts?
https://github.com/users/KentoNishi/projects/1

**Comment by rahulkaura2004** [comment]
I will sign up

**Comment by rahulkaura2004** [comment]
Signed up, Kento I will add you as a partner with me and Thomas because you also worked on it.

**Comment by KentoNishi** [comment]
What partner?

**Comment by KentoNishi** [comment]
Alex is also doing the hackathon...

**Comment by rahulkaura2004** [comment]
Great! I meant partner for the program auto routine

**Comment by Rahul-Kaura** [comment]
If you need any help just let me know!

**Comment by Rahul-Kaura** [comment]
What work do we have remaining on auto Integration that I can help implement with my Java skills!

**Pull request merged**
