### PR TITLE
Get the screen record and gui working 

### PR DESCRIPTION
**Pull request by lithomas1**
Goals
1. Make GUI work
2. Make screen capture work
3. Mouse and keyboard detection?

### CODE REVIEW

**Comment by Rahul-Kaura** [comment]
Thomas, what are we trying to have as the final outcome of this project for the next hackathon?

**Comment by lithomas1** [comment]
This thing should be able to record your mouse and key movements and be able to do the same actions itself. Afterwards can you review my code when I mark this pull request as ready to merge?

**Comment by Rahul-Kaura** [comment]
This can be solved using the mouse listener in Java. It is very simple functionality and I can help you integrate it as it is very easy to use. We need to move on to the next step of this project because I already know how to track mouse movements and keyboard movements

**Comment by Rahul-Kaura** [comment]
If you need anything more of me just right a comment on this file, if there is something I can do.

**Comment by lithomas1** [comment]
alright then fix my gui pls
go to hangouts

**Comment by Rahul-Kaura** [comment]
No problem, Send me the code

**Comment by Rahul-Kaura** [comment]
What is going to be the final outcome of this project, after we finish implementing the mouse and key listener.

**Comment by rahulkaura2004** [comment]
I will just post your code to the GitHub Repository

**Comment by rahulkaura2004** [comment]
Post your code to the GitHub Repository so I can edit it after you help me
with Terminal!

From,
Rahul

**Comment by lithomas1** [comment]
i'll talk to you later. Don't comment on this anymore unless you are code reviewing as it clutters it up.

**Comment by lithomas1** [comment]
Hey Rahul, can you make the GUI unbroken, I'm going to work on the backend now?

**Comment by lithomas1** [comment]
> 
> 
> wdym still broken XD

Gonna force Rahul to fix. Can you code review my trash code?

**Comment by KentoNishi** [comment]
I have no idea how to do Java UI

**Comment by lithomas1** [comment]
> 
> 
> I have no idea how to do Java UI

rip, alright rahul can do it because i don't want to :(

**Review by KentoNishi — DISMISSED** [review]
Fix merge conflicts in FxGUI.fxml.

**Comment by KentoNishi** [comment]
Can I merge this yet?

**Comment by Rahul-Kaura** [comment]
Yeah merge it, if it works and yeah!!

From,
Rahul

**Comment by KentoNishi** [comment]
I have no idea what this even does, cuz I don't have Java or Eclipse installed

**Pull request merged**
